# Generated by Django 3.1.2 on 2021-02-14 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "currency_pair",
                    models.CharField(
                        choices=[
                            ("BTC_USD", "BTC/USD"),
                            ("BTC_EUR", "BTC/EUR"),
                            ("BCH_USD", "BCH/USD"),
                            ("BCH_EUR", "BCH/EUR"),
                            ("ETH_USD", "ETH/USD"),
                            ("ETH_EUR", "ETH/EUR"),
                            ("BNB_BTC", "BNB/BTC"),
                        ],
                        max_length=255,
                    ),
                ),
                ("last_ask_price", models.FloatField(null=True)),
                ("last_bid_price", models.FloatField(null=True)),
                ("api_data", models.TextField(default="{}")),
            ],
            options={"db_table": "exchange", "ordering": ["-name"]},
        ),
        migrations.CreateModel(
            name="Tri_Spread",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tri_exchange_buy1_id", models.IntegerField()),
                ("tri_exchange_sell_id", models.IntegerField()),
                ("tri_exchange_buy2_id", models.IntegerField()),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
                ("tri_spread", models.FloatField(blank=True)),
                (
                    "tri_xchange_buy1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tri_exchange_buy1",
                        to="arbitrage.exchange",
                    ),
                ),
                (
                    "tri_xchange_buy2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tri_exchange_buy2",
                        to="arbitrage.exchange",
                    ),
                ),
                (
                    "tri_xchange_sell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tri_exchange_sell",
                        to="arbitrage.exchange",
                    ),
                ),
            ],
            options={"db_table": "tri_spread", "ordering": ["-recorded_date"]},
        ),
        migrations.CreateModel(
            name="Spread",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exchange_buy_id", models.IntegerField()),
                ("exchange_sell_id", models.IntegerField()),
                ("recorded_date", models.DateTimeField(auto_now_add=True)),
                ("spread", models.IntegerField(blank=True)),
                (
                    "xchange_buy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_buy",
                        to="arbitrage.exchange",
                    ),
                ),
                (
                    "xchange_sell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_sell",
                        to="arbitrage.exchange",
                    ),
                ),
            ],
            options={"db_table": "spread", "ordering": ["-recorded_date"]},
        ),
    ]
